import { Router } from 'express';
import authRoutes from '../../modules/auth/auth.routes';
import employeesRoutes from '../../modules/employees/employees.routes';
import departmentsRoutes from '../../modules/departments/departments.routes';
import tasksRoutes from '../../modules/tasks/tasks.routes';
import projectsRoutes from '../../modules/projects/projects.routes';
import attendanceRoutes from '../../modules/attendance/attendance.routes';
import timesheetRoutes from '../../modules/timesheet/timesheet.routes';
import vacationsRoutes from '../../modules/vacations/vacations.routes';
import tripsRoutes from '../../modules/trips/trips.routes';
import sickleavesRoutes from '../../modules/sickleaves/sickleaves.routes';
import filesRoutes from '../../modules/files/files.routes';
import calendarRoutes from '../../modules/calendar/calendar.routes';
import reportsRoutes from '../../modules/reports/reports.routes';
import notificationsRoutes from '../../modules/notifications/notifications.routes';
import workflowRoutes from '../../modules/workflow/workflow.routes';
import delegationRoutes from '../../modules/delegation/delegation.routes';
import resolutionRoutes from '../../modules/resolutions/resolution.routes';
import ticketRoutes from '../../modules/service-desk/ticket.routes';
import taskHistoryRoutes from '../../modules/tasks/task-history.routes';
import chatRoutes from '../../modules/chat/chat.routes';
import meetingsRoutes from '../../modules/meetings/meetings.routes';
import documentsRoutes from '../../modules/documents/documents.routes';
import kpiRoutes from '../../modules/kpi/kpi.routes';
import syncRoutes from '../../modules/sync/sync.routes';
import newsRoutes from '../../modules/news/news.routes';
import announcementsRoutes from '../../modules/announcements/announcements.routes';
import auditLogRoutes from '../../modules/audit-log/audit-log.routes';
import payrollRoutes from '../../modules/payroll/payroll.routes';
import staffRoutes from '../../modules/staff/staff.routes';
import foldersRoutes from '../../modules/folders/folders.routes';
import workspacesRoutes from '../../modules/workspaces/workspaces.routes';
import memosRoutes from '../../modules/memos/memos.routes';
import taskDependenciesRoutes from '../../modules/tasks/task-dependencies.routes';
import templatesRoutes from '../../modules/templates/templates.routes';
import dashboardRoutes from '../../modules/dashboard/dashboard.routes';
import searchRoutes from '../../modules/search/search.routes';
import automationRoutes from '../../modules/automation/automation.routes';
import feedRoutes from '../../modules/feed/feed.routes';
import notesRoutes from '../../modules/notes/notes.routes';
import invitationsRoutes from '../../modules/invitations/invitations.routes';
import taskChatsRoutes from '../../modules/chat/task-chats.routes';
import aiRoutes from '../../modules/ai/ai.routes';

const routes = Router();

// API Маршруты
routes.use('/auth', authRoutes);
routes.use('/employees', employeesRoutes);
routes.use('/departments', departmentsRoutes);
routes.use('/tasks', taskDependenciesRoutes);
routes.use('/tasks', tasksRoutes);
routes.use('/projects', projectsRoutes);
routes.use('/attendance', attendanceRoutes);
routes.use('/timesheet', timesheetRoutes);
routes.use('/vacations', vacationsRoutes);
routes.use('/trips', tripsRoutes);
routes.use('/sickleaves', sickleavesRoutes);
routes.use('/files', filesRoutes);
routes.use('/calendar', calendarRoutes);
routes.use('/reports', reportsRoutes);
routes.use('/notifications', notificationsRoutes);
routes.use('/workflow', workflowRoutes);
routes.use('/delegation', delegationRoutes);
routes.use('/resolutions', resolutionRoutes);
routes.use('/tickets', ticketRoutes);
routes.use('/', taskHistoryRoutes);
routes.use('/chat', chatRoutes);
routes.use('/meetings', meetingsRoutes);
routes.use('/documents', documentsRoutes);
routes.use('/kpi', kpiRoutes);
routes.use('/sync', syncRoutes);
routes.use('/news', newsRoutes);
routes.use('/announcements', announcementsRoutes);
routes.use('/audit-logs', auditLogRoutes);
routes.use('/payroll', payrollRoutes);
routes.use('/staff', staffRoutes);
routes.use('/folders', foldersRoutes);
routes.use('/workspaces', workspacesRoutes);
routes.use('/memos', memosRoutes);
routes.use('/templates', templatesRoutes);
routes.use('/dashboard', dashboardRoutes);
routes.use('/search', searchRoutes);
routes.use('/automation', automationRoutes);
routes.use('/feed', feedRoutes);
routes.use('/notes', notesRoutes);
routes.use('/invitations', invitationsRoutes);
routes.use('/task-chats', taskChatsRoutes);
routes.use('/ai', aiRoutes);

export { routes };
